version: '3'

networks:
  api:

services:
  nginx:
    image: nginx:alpine
    container_name: api-nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - api

  mysql:
    image: mysql:8.0
    container_name: api-mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - api

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-php
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:9000
    networks:
      - api

  composer:
    image: composer:latest
    container_name: api-composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - api
    entrypoint: [ "composer" ]

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - api
